all: RDF_O RDF_SiO RDF_Silica RDF_Si density energy BAD_osio BAD_siosi

energy:energy.gp
	gnuplot energy.gp

density:density.gp
	gnuplot density.gp

RDF_O:RDF_O.gp
	gnuplot RDF_O.gp

RDF_SiO:RDF_SiO.gp
	gnuplot RDF_SiO.gp

RDF_Silica:RDF_Silica.gp
	gnuplot RDF_Silica.gp

RDF_Si:RDF_Si.gp
	gnuplot RDF_Si.gp

BAD_osio:osio.gp
	gnuplot osio.gp

BAD_siosi:siosi.gp
	gnuplot siosi.gp

